const splittedScriptFile = [
  `// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;

`,
  `
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}

`,
  `{
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }

  public void Dispose()
  {
    driver.Quit();
  }
  
  // Starting place to merge files
`,
  `}`,
];

export function InsertTestFunction(
  SuiteTestName: string,
  ...functions: string[]
): string {
  const newScript = [
    splittedScriptFile[0],
    `public class ${SuiteTestName} : IDisposable {`,
    splittedScriptFile[1],
    `  public ${SuiteTestName}()`,
    splittedScriptFile[2],
    ...functions,
    splittedScriptFile[3],
  ];
  return newScript.join('\n');
}
